# -*- coding: utf-8 -*-
"""data_cleaning_challenge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qm0PMDwPHdfOvFW2e2wF2bIEz0rgDE0w
"""

import pandas as pd

data_import = pd.read_csv("data_cleaning_challenge.csv")
data_import

data_drop = data_import.drop(columns=["Unnamed: 9", "Unnamed: 10"])
data_drop

no_nan = data_drop[data_drop["Row Type"].notna()]
no_nan

column_values = []
iteration = 0

for i in no_nan["Row Type"]:
    if "first name" in i:
        iteration += 1
    column_values.append(iteration)

iter_column_added = no_nan
iter_column_added["Iteration"] = column_values
iter_column_added

drop_extra_column_rows = iter_column_added[iter_column_added["Row Type"] != "Row Type"]
drop_extra_column_rows

name_dataframe = drop_extra_column_rows[drop_extra_column_rows["Row Type"].str.contains("first name")]
name_dataframe

name_dataframe = name_dataframe.loc[:,["Row Type", "Iter Number", "Power1", "Iteration"]]
name_dataframe.rename(columns={"Row Type": "First Name", "Iter Number":"Last Name", "Power1": "Date"}, inplace=True)
name_dataframe["First Name"] = name_dataframe["First Name"].str[12:]
name_dataframe["Last Name"] = name_dataframe["Last Name"].str[10:]
name_dataframe["Date"] = name_dataframe["Date"].str[5:]
name_dataframe

no_name_dataframe = drop_extra_column_rows[~drop_extra_column_rows["Row Type"].str.contains("first name")]
no_name_dataframe

pd.merge(left=name_dataframe, right=no_name_dataframe, how="inner", on="Iteration")

